sylius_fixtures:
    suites:
        default:
            fixtures:
                geographical:
                    options:
                        countries:
                            - 'DK'
                            - 'SE'
                            - 'FI'

                            # @todo Remove all other countries once https://github.com/Sylius/Sylius/issues/11216 fixed
                            - 'US'
                            - 'FR'
                            - 'DE'
                            - 'AU'
                            - 'CA'
                            - 'MX'
                            - 'NZ'
                            - 'PT'
                            - 'ES'
                            - 'CN'
                            - 'UK'
                            - 'NL'
                            - 'BE'
                        zones:
                            WORLD:
                                name: 'World'
                                countries:
                                    - 'DK'
                                    - 'SE'
                                    - 'FI'
                                    - 'US'
                                    - 'FR'
                                    - 'DE'
                                    - 'AU'
                                    - 'CA'
                                    - 'MX'
                                    - 'NZ'
                                    - 'PT'
                                    - 'ES'
                                    - 'CN'
                                    - 'UK'
                                    - 'NL'
                                    - 'BE'
                            DAO_PP_COUNTRIES:
                                name: 'Denmark'
                                countries:
                                    # Dao operates at DK only
                                    - 'DK'
                            POSTNORD_PP_COUNTRIES:
                                name: 'PostNord countries'
                                countries:
                                    - 'DK'
                                    - 'SE'
                                    - 'FI'
                            GLS_PP_COUNTRIES:
                                name: 'GLS countries'
                                countries:
                                    - 'DK'
                                    - 'SE'
                                    - 'FI'
                                    - 'FR'
                                    - 'DE'
                                    - 'PT'
                                    - 'ES'
                                    - 'UK'
                            BPOST_PP_COUNTRIES:
                                name: 'Bpost countries'
                                countries:
                                    - 'NL'
                                    - 'BE'
                            POSTNL_PP_COUNTRIES:
                                name: 'PostNL countries'
                                countries:
                                    - 'NL'
                                    - 'BE'

                setono_sylius_pickup_point_shipping_method:
                    options:
                        custom:
                            dao_pickup_point:
                                code: "dao_pickup_point"
                                name: "DAO with pickup points"
                                enabled: true
                                zone: "DAO_PP_COUNTRIES"
                                pickup_point_provider: dao
                                channels:
                                    - "FASHION_WEB"
                            gls_pickup_point:
                                code: "gls_pickup_point"
                                name: "GLS with pickup points"
                                enabled: true
                                zone: "WORLD"
                                pickup_point_provider: gls
                                channels:
                                    - "FASHION_WEB"
                            gls_home:
                                code: "gls_home"
                                name: "GLS home delivery"
                                enabled: true
                                zone: "WORLD"
                                channels:
                                    - "FASHION_WEB"
                            post_nord_pickup_point:
                                code: "post_nord_pickup_point"
                                name: "PostNord with pickup points"
                                enabled: true
                                zone: "POSTNORD_PP_COUNTRIES"
                                pickup_point_provider: post_nord
                                channels:
                                    - "FASHION_WEB"
                            post_nord_home:
                                code: "post_nord_home"
                                name: "PostNord home delivery"
                                enabled: true
                                zone: "WORLD"
                                channels:
                                    - "FASHION_WEB"
                            postnl_pickup_point:
                                code: "postnl_pickup_point"
                                name: "PostNL with pickup points"
                                enabled: true
                                zone: "POSTNL_PP_COUNTRIES"
                                pickup_point_provider: postnl
                                channels:
                                    - "FASHION_WEB"
                            bpost_pickup_point:
                                code: "bpost_pickup_point"
                                name: "Bpost with pickup points"
                                enabled: true
                                zone: "BPOST_PP_COUNTRIES"
                                pickup_point_provider: bpost
                                channels:
                                    - "FASHION_WEB"
                            faker:
                                code: "faker"
                                name: "Fake delivery"
                                enabled: true
                                zone: "WORLD"
                                pickup_point_provider: faker
                                channels:
                                    - "FASHION_WEB"
